# Generated by Django 3.2.4 on 2023-06-23 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('seller_type', models.PositiveSmallIntegerField(choices=[(1, 'CREATOR'), (2, 'AFFILIATE')], verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='SalesTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=30, verbose_name='Product Description')),
                ('price', models.PositiveIntegerField(verbose_name='Transaction value (in Cents)')),
                ('purchased_date', models.DateTimeField(verbose_name='Purchased Date')),
                ('sale_type', models.PositiveSmallIntegerField(choices=[(1, 'CREATOR_SALE'), (2, 'AFFILIATED_SALE'), (3, 'COMMISSION_PAID'), (4, 'COMMISSION_RECEIVED')], verbose_name='Type')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.seller', verbose_name='Seller')),
            ],
        ),
    ]
