version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    depends_on:
      - db
    env_file:
      - ./src/.env

  db:
    image: postgres:alpine
    container_name: postgres_server
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
